# Generated by Django 2.2.24 on 2021-12-13 01:05

from django.db import migrations


def fill_owners(apps, schema_editor):
    try:
        Flat = apps.get_model('property', 'Flat')
        Owner = apps.get_model('property', 'Owner')
    except LookupError:
        return None

    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owners_pure_phone=flat.owners_pure_phone,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_owner'),
    ]

    operations = [
        migrations.RunPython(fill_owners)
    ]
